### ISSUE TITLE
How many points? (sources/targets)

### ISSUE THREAD

**Issue by labarba** [barbagroup/bempp_exafmm_paper#4]
In the performance section of results, Fig. 13 (timing vs. N, showing linear complexity) says "number of elements" in the x-axis label. The data point at largest N shows 2x10^6. 

In the text, it says "in the largest case, with over 10 million quadrature points." It's implicit, then, that the figure plots w.r.t. the number of _elements_, as it says. It would be good to be explicit in the caption by mentioning the number of quadrature points per triangle, and stating the largest N is so-many points. 

Elsewhere, too: captions of Table 4, Figs. 14, 15. Also, section 3.5: the Zika virus is discretized with 10 million elements. Is this 6 quadrature points per triangle, leading to 60 million FMM points? Say that.

**Comment by labarba** [comment]
Ha! Found that it says for the Zika virus 3 quad points per triangle are used. So it's 30 million points?

**Comment by tingyu66** [comment]
Yes. I have added this information to our result. In addition, we now report the number of quadrature points instead of the quadrature order.
